
FROM mysql:5.5.52

# Since this database is just running on the local computer and is not exposed
# to the open internet, a blank password is acceptable.
# All other tiers (dev/prod) are secured by a password.
ENV MYSQL_ALLOW_EMPTY_PASSWORD='yes'

EXPOSE 3306
