
FROM ubuntu:trusty

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y \
    apache2 \
    php5 \
    php5-dev \
    libapache2-mod-php5 \
    php-calendar \
    php5-cgi \
    php5-cli \
    php5-common \
    php5-curl \
    php5-enchant \
    php5-gd \
    php5-gmp \
    php5-imap \
    php5-intl \
    php5-json \
    php5-ldap \
    php5-mcrypt \
    php5-mysql \
    php5-odbc \
    php5-pgsql \
    php5-pspell \
    php5-readline \
    php5-recode \
    php5-sqlite \
    php5-sybase \
    php5-tidy \
    php5-xmlrpc \
    php5-xsl

COPY ./docker/000-default.conf /etc/apache2/sites-enabled/000-default.conf

RUN a2enmod rewrite

COPY .env.local /var/secrets/.env
RUN chgrp www-data /var/secrets/.env && \
    chmod g+r /var/secrets/.env

# Invoke custom script to ensure that the Apache server reliably starts.
# Copied from the official PHP image in the Docker library.
#
# Source:
# https://github.com/docker-library/php/commit/a51c16e5f91be6243452471d1454dca5b168e3d4
COPY ./docker/apache2-foreground.sh /usr/local/bin/apache2-foreground
CMD ["apache2-foreground"]

EXPOSE 80
