version: "3"
services:
  webapp:
    stop_signal: SIGWINCH
    build:
      context: ./
      dockerfile: Dockerfile-webapp
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html/~bfgodfr/4620/project
  db:
    build:
      context: ./
      dockerfile: Dockerfile-db
    ports:
      - "3306:3306"
    env_file: .env.local
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env.local
    restart: always
    ports:
      - 8080:80
